// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRrL7dO8VgnuWHqRYEXVUmfLsZ5z5Tugw',
    appId: '1:489409977545:web:1601bbd09e939d2c100118',
    messagingSenderId: '489409977545',
    projectId: 'cute-hamong-3a3aa',
    authDomain: 'cute-hamong-3a3aa.firebaseapp.com',
    storageBucket: 'cute-hamong-3a3aa.firebasestorage.app',
    measurementId: 'G-P4RN8HS9B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iaUaKc1iOMaVrfOvOmjkhnHPbEceQ7Y',
    appId: '1:489409977545:android:454f8c46ec08b59f100118',
    messagingSenderId: '489409977545',
    projectId: 'cute-hamong-3a3aa',
    storageBucket: 'cute-hamong-3a3aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_TqC0mme0-Gp3dMXHZbDWcLpYyb4sw8',
    appId: '1:489409977545:ios:84f56b34a63af9da100118',
    messagingSenderId: '489409977545',
    projectId: 'cute-hamong-3a3aa',
    storageBucket: 'cute-hamong-3a3aa.firebasestorage.app',
    iosBundleId: 'com.example.cuteHamong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_TqC0mme0-Gp3dMXHZbDWcLpYyb4sw8',
    appId: '1:489409977545:ios:84f56b34a63af9da100118',
    messagingSenderId: '489409977545',
    projectId: 'cute-hamong-3a3aa',
    storageBucket: 'cute-hamong-3a3aa.firebasestorage.app',
    iosBundleId: 'com.example.cuteHamong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRrL7dO8VgnuWHqRYEXVUmfLsZ5z5Tugw',
    appId: '1:489409977545:web:61f825f96ca17dbb100118',
    messagingSenderId: '489409977545',
    projectId: 'cute-hamong-3a3aa',
    authDomain: 'cute-hamong-3a3aa.firebaseapp.com',
    storageBucket: 'cute-hamong-3a3aa.firebasestorage.app',
    measurementId: 'G-RLVYE4HGD3',
  );

}